build:
  version: "3.0"

loans:
  message : "Welcome to EazyBank loans related qa APIs"
  contactDetails:
    name: "Ankit Bisen- Java Developer"
    email: "akitbisen21@gmail.com"
  onCallSupport:
    -1234567890
    -0987654321