build:
  version: "3.0"

cards:
  message : "Welcome to EazyBank Cards related prod APIs"
  contactDetails:
    name: "Ankit Bisen- Java Developer"
    email: "akitbisen21@gmail.com"
  onCallSupport:
    -1234567890
    -0987654321