spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "file:///D://Java Developer Complete Package//config"    #Reading configuration from a file system location.
          #search-locations: "classpath:/config"      #Reading configuration from a classpath location configserver repo
        git:
          uri: "https://github.com/bisenankit21/ConfigRepo.git"
          default-label: "master"
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"

encrypt:
  key: "4453j44i34jk3h4i347934893i"
server:
  port: 8071